name = "Cozy Create"
author = "Kavikick"
version = "0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1aecd65924906a2e33f01fde79af83aa452c456a0a67c76dc9d305940a7820b9"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
