name = "Cozy Create"
author = "Kavikick"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "24dacf310a1d0748d1eccfc0930a615ec41a8f4d80aa3881bc6f8c0f684c6102"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
