name = "Cozy Create"
author = "Kavikick"
version = "0.3.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff73a7e34866bbd531a5e82950dd3475b1d499a44a230ee2fcdc0afbfde85483"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
